### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by Vladut41** [iPERDance/iPERCore#108]
raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by d1ddle** [comment]
Can I add to this?

`./assets/executables/ffmpeg-4.3.1-win64-static/bin/ffprobe.exe -show_entries stream=codec_type -of json` `./assets/samples/references/akun_2.mp4 -loglevel error`
`'.' is not recognized as an internal or external command,`
`operable program or batch file.`

[...]

`File "c:\python38\lib\json\decoder.py", line 355, in raw_decode`
    `raise JSONDecodeError("Expecting value", s, err.value) from None`
`json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by StevenLiuWen** [comment]
@d1ddle, https://github.com/iPERDance/iPERCore/blob/main/docs/install.md#download-checkpoints-and-samples.
you need to download the **sampels.zip** and unzip the **samples.zip** to **assets** which contains the example videos.

**Comment by d1ddle** [comment]
Hi, @StevenLiuWen 
Unfortunately that didn't solve the issue, and I ended up having to alter video.py a bit:
Replace line 676 in `.\iPERCore\iPERCore\tools\utils\multimedia\video.py` with:
`cmd = f""""{ffprobe_exe_path}" -show_entries stream=codec_type -of json "{video_path}" -loglevel error"""`

I'm trying to run from source on Windows but have some other issues #107

**Comment by justinjohn0306** [comment]
Same here...

**Comment by Vladut41** [comment]
> Hi, @StevenLiuWen
> Unfortunately that didn't solve the issue, and I ended up having to alter video.py a bit:
> 
> Replace line 676 in `.\iPERCore\iPERCore\tools\utils\multimedia\video.py` with:
> `cmd = f""""{ffprobe_exe_path}" -show_entries stream=codec_type -of json "{video_path}" -loglevel error"""`
> 
> @Vladut41 let me know if this fixes your issue
> 
> I'm trying to run from source on Windows but have some other issues #107

I still get the same issue

**Comment by d1ddle** [comment]
Just above where your error occurred in your previous comment, what error were you getting?

**Comment by Vladut41** [comment]
> Just above where your error occurred in your previous comment, what error were you getting?

![error1](https://user-images.githubusercontent.com/73821804/115448163-0ddb5d80-a222-11eb-87d3-2eefee4d0506.PNG)

**Comment by d1ddle** [comment]
Ok, that's progression;
Can you see where it errors in `./iPERCore/tools/utils/multimedia/video.py` line 680? That's because of a simple typo.
In python, when you need to use double quotes (") in a string, you need to surround the string with triple quotes;
`message = ("""str"i"ng""")`
In video.py, line 676, `cmd` is defined without triple quotes, like this:
`cmd = f"{ffprobe_exe_path} -show_entries stream=codec_type -of json {video_path} -loglevel error"`
Which means the files that are run in the terminal aren't referenced in quotes, which they need to be.
Valid EG: `C:\>"./ffmpeg/bin/ffmpeg.exe" -show_entries`

So to fix this:
Replace line 676 in .\iPERCore\iPERCore\tools\utils\multimedia\video.py with:
cmd = f""""{ffprobe_exe_path}" -show_entries stream=codec_type -of json "{video_path}" -loglevel error"""

In my issue #107 , I mentioned how I noticed `main` has been changed quite a bit since the Windows release.
Now this has become more apparent.

**Comment by d1ddle** [comment]
That's weird, I commented and realised in line 1 that the command was called right, but it still errors in the same place.
Maybe it's something to do with anaconda.

**Comment by Vladut41** [comment]
> That's weird; at first I commented but then realised in line 1 that the command was called right, but it still errors in the same place.
> ~Maybe it's something to do with anaconda.~
> 
> **EDIT**: Make sure you have downloaded the samples and checkpoint files like @StevenLiuWen said; I can see a
> `System cannot find the path specified`
> 
> Don't need this but I'll leave it
> My environment was setup with the pip library virtualenv.
> `pip install virtualenv`
> `virtualenv venv`
> `cd ./venv/scripts`
> `activate.bat`
> Virtual environment!
> 
> I have never used anaconda, so I'm not quite sure how it works compared to virtualenv.

Ok so, I removed the ".mp4" after the name of the video in the code and it worked, but now I have No module named 'mmedit' error...

**Comment by d1ddle** [comment]
Compiling from Windows will always get you issues I assume. As far as I know, the mmcv-full=1.2.0+torch=0.7.0+cu101 for Windows doesn't exist, doesn't compile the wheel properly of Windows and therefore stopped my from progressing furtur with the installation. However since last week I might have another go at this with the following:
 - Copying the mmcv-full folder from the binary release leaves a __version__ error, so I might try with some dev scripts..
 - Booting a Ubuntu 16.04 VM and compiling a Windows mmcv wheel..
 - Trying to get the whole project to compile/work at all on Ubuntu..
I'll update this thread when I get around to doing any if any..

**Comment by StevenLiuWen** [comment]
Hi @Vladut41 , we have fixed the bugs, https://github.com/iPERDance/iPERCore/commit/1c15b8208a4313c91ce6bf7a97a15fe43cee4a74 and try to update the codes.

**Comment by Vladut41** [comment]
@StevenLiuWen Thanks! It's working now, but when I use two source images I'm getting this error "RuntimeError: cuda runtime error (100) : no CUDA-capable device is detected at ..\aten\src\THC\THCGeneral.cpp:47"

**Comment by StevenLiuWen** [comment]
Hi @Vladut41, changing the `--gpu_ids 2` to `--gpu_ids 0`.
