### ISSUE TITLE
Character is tied to the center of the frame

### ISSUE THREAD

**Issue by remixer-dec** [iPERDance/iPERCore#22]
I noticed that in the demo on your website, a character can move around in the frame, but in the Colab demo it seems, that a character is always locked to the center of the frame.  
![Screenshot](https://i.imgur.com/M0FPEYk_d.png)  
Is this by design? Can you make this configurable?

**Comment by piaozhx** [comment]
You are right. The Colab version is using an algorithm to make the camera and pose smoother. We found that the horizontal movement is useless and may introduce some noise in many cases, so we **set it to 0** (that's why the character is always locked to the center of the frame). We will consider making it configurable in the future version.

**Comment by remixer-dec** [comment]
Got it. Well, it might be noisy, but it feels more realistic in some cases, It would be nice to have such option. 
P.S. Thank you guys, for making such a great project, the results are really impressive!

**Comment by piaozhx** [comment]
Thanks!
